name: PlotSquared
main: com.plotsquared.bukkit.BukkitPlatform
api-version: "1.13"
version: "${version}"
load: STARTUP
description: "Easy, yet powerful Plot World generation and management."
authors: [Citymonstret, Empire92, MattBDev, dordsor21, NotMyFault, SirYwell]
website: https://www.spigotmc.org/resources/77506/
softdepend: [Vault, PlaceholderAPI, Essentials, LuckPerms, BungeePerms, MVdWPlaceholderAPI]
loadbefore: [MultiWorld, Multiverse-Core]
depend: [WorldEdit]
database: false
commands:
  plots:
    description: Plot command.
    aliases: [p,plot,ps,plotsquared,p2,2,plotme]
    permission: plots.use
    permission-message: "You are lacking the permission node 'plots.use'"
permissions:
  plots.use:
    default: true
  plots.projectile.unowned:
    default: false
  plots.projectile.other:
    default: false
  plots.toggle.titles:
    default: false
  plots.toggle.chat:
    default: false
  plots.toggle.time:
    default: false
  plots.merge.other:
    default: false
  plots.merge.keeproad.denied:
    default: false
  plots.trust.everyone:
    default: false
  plots.area.create:
    default: false
  plots.area.info:
    default: false
  plots.area.list:
    default: false
  plots.area.regen:
    default: false
  plots.area.tp:
    default: false
  plots.auto.mega:
    default: false
  plots.continue:
    default: false
  plots.cluster.list:
    default: false
  plots.cluster.create:
    default: false
  plots.cluster.create.other:
    default: false
  plots.cluster.size:
    default: false
  plots.cluster.delete.other:
    default: false
  plots.cluster.resize:
    default: false
  plots.cluster.resize.other:
    default: false
  plots.cluster.resize.shrink:
    default: false
  plots.cluster.resize.expand:
    default: false
  plots.cluster:
    default: false
  plots.cluster.invite:
    default: false
  plots.cluster.invite.other:
    default: false
  plots.cluster.kick:
    default: false
  plots.cluster.kick.other:
    default: false
  plots.cluster.leave:
    default: false
  plots.cluster.tp:
    default: false
  plots.cluster.tp.other:
    default: false
  plots.cluster.sethome:
    default: false
  plots.cluster.sethome.other:
    default: false
  plots.cluster.command.continue:
    default: false
  plots.deny.everyone:
    default: false
  plots.download.world:
    default: false
  plots.set.flag.other:
    default: false
  plots.set:
    default: false
  plots.set.biome:
    default: false
  plots.set.alias:
    default: false
  plots.set.home:
    default: false
  plots.set.main:
    default: false
  plots.set.floor:
    default: false
  plots.set.air:
    default: false
  plots.set.all:
    default: false
  plots.set.border:
    default: false
  plots.set.wall:
    default: false
  plots.set.outline:
    default: false
  plots.set.middle:
    default: false
  plots.set.flag:
    default: false
  plots.flag.remove:
    default: false
  plots.flag.list:
    default: false
  plots.list.forsale:
    default: false
  plots.list.mine:
    default: false
  plots.list.shared:
    default: false
  plots.target:
    default: false
  plots.list.world:
    default: false
  plots.list.top:
    default: false
  plots.list.all:
    default: false
  plots.list.unowned:
    default: false
  plots.list.player:
    default: false
  plots.list.done:
    default: false
  plots.list.expired:
    default: false
  plots.list.fuzzy:
    default: false
  plots.list.area:
    default: false
  plots.comment:
    default: false
  plots.schematic.paste:
    default: false
  plots.schematic.list:
    default: false
  plots.schematic.save:
    default: false
  plots.visit.shared:
    default: false
  plots.visit.unowned:
    default: false
  plots.visit.owned:
    default: false
  plots.visit.other:
    default: false
  plots.visit.denied:
    default: false
  plots.home:
    default: false
  plots.alias.remove:
    default: false
  plots.backup:
    default: false
  plots.backup.save:
    default: false
  plots.backup.list:
    default: false
  plots.backup.load:
    default: false
  plots.rate:
    default: false
  plots.template.export:
    default: false
  plots.template.import:
    default: false
  plots.template:
    default: false
  plots.components:
    default: false

  plots.admin:
    default: false
  plots.admin.command.continue:
    default: false
  plots.admin.command.delete:
    default: false
  plots.admin.command.deny:
    default: false
  plots.admin.command.done:
    default: false
  plots.admin.command.download:
    default: false
  plots.admin.command.kick:
    default: false
  plots.admin.command.load:
    default: false
  plots.admin.command.merge:
    default: false
  plots.admin.command.setowner:
    default: false
  plots.admin.command.remove:
    default: false
  plots.admin.command.save:
    default: false
  plots.admin.command.schematic.paste:
    default: false
  plots.admin.command.schematic.save:
    default: false
  plots.admin.command.unlink:
    default: false
  plots.admin.alias.set:
    default: false
  plots.admin.alias.remove:
    default: false
  plots.admin.chat.bypass:
    default: false
  plots.admin.backup.other:
    default: false
  plots.admin.unsafe:
    default: false
  plots.admin.debug.other:
    default: false
  plots.admin.area.sudo:
    default: false
  plots.admin.interact.blockedcommands:
    default: false
  plots.admin.update.notify:
    default: false
  plots.admin.exit.denied:
    default: false
  plots.admin.entry.denied:
    default: false
  plots.admin.visit.untrusted:
    default: false
  plots.admin.entry.forcefield:
    default: false
  plots.admin.command.chatspy:
    default: false
  plots.admin.caps.other:
    default: false
  plots.admin.music.other:
    default: false
  plots.admin.destroy.unowned:
    default: false
  plots.admin.destroy.groundlevel:
    default: false
  plots.admin.destroy.other:
    default: false
  plots.admin.destroy.road:
    default: false
  plots.admin.build.road:
    default: false
  plots.admin.build.unowned:
    default: false
  plots.admin.build.other:
    default: false
  plots.admin.interact.road:
    default: false
  plots.admin.interact.unowned:
    default: false
  plots.admin.interact.other:
    default: false
  plots.admin.build.heightlimit:
    default: false
  plots.admin.command.purge.ratings:
    default: false
  plots.admin.command.trust:
    default: false
  plots.admin.command.add:
    default: false
  plots.admin.info.force:
    default: false
  plots.admin.command.schematic:
    default: false
  plots.admin.command.clear:
    default: false
  plots.admin.flight:
    default: false
  plots.admin.command.blocked-cmds.shared:
    default: false
  plots.admin.command.blocked-cmds.road:
    default: false
  plots.admin.components.other:
    default: false

  plots.teleport.delay.bypass:
    default: false
  plots.worldedit.bypass:
    default: false
  plots.gamemode.bypass:
    default: false
  plots.confirm.bypass:
    default: false
  plots.flag.notify-enter.bypass:
    default: false
  plots.flag.notify-leave.bypass:
    default: false

  plots.permpack.basicflags:
    default: false
    children:
      plots.set.flag: true
      plots.flag: true
      plots.flag.add: true
      plots.flag.remove: true
      plots.flag.list: true
      plots.flag.info: true
      plots.set.flag.titles: true
      plots.set.flag.titles.*: true
      plots.set.flag.description: true
      plots.set.flag.greeting: true
      plots.set.flag.farewell: true
      plots.set.flag.notify-enter: true
      plots.set.flag.notify-enter.*: true
      plots.set.flag.notify-leave: true
      plots.set.flag.notify-leave.*: true
      plots.set.flag.feed: true
      plots.set.flag.feed.*: true
      plots.set.flag.heal: true
      plots.set.flag.heal.*: true
      plots.set.flag.invincible: true
      plots.set.flag.invincible.*: true
      plots.set.flag.instabreak: true
      plots.set.flag.instabreak.*: true
      plots.set.flag.fly: true
      plots.set.flag.fly.*: true
      plots.set.flag.gamemode: true
      plots.set.flag.gamemode.creative: true
      plots.set.flag.gamemode.survival: true
      plots.set.flag.gamemode.adventure: true
      plots.set.flag.time: true
      plots.set.flag.weather: true
      plots.set.flag.weather.*: true
      plots.set.flag.music: true
      plots.set.flag.music.*: true
      plots.set.flag.disable-physics: true
      plots.set.flag.disable-physics.*: true
      plots.set.flag.pve: true
      plots.set.flag.pve.*: true
      plots.set.flag.pvp: true
      plots.set.flag.pvp.*: true
      plots.set.flag.explosion: true
      plots.set.flag.explosion.*: true
      plots.set.flag.hostile-interact: true
      plots.set.flag.hostile-interact.*: true
      plots.set.flag.hostile-attack: true
      plots.set.flag.hostile-attack.*: true
      plots.set.flag.player-interact: true
      plots.set.flag.player-interact.*: true
      plots.set.flag.animal-interact: true
      plots.set.flag.animal-interact.*: true
      plots.set.flag.animal-attack: true
      plots.set.flag.animal-attack.*: true
      plots.set.flag.tamed-interact: true
      plots.set.flag.tamed-interact.*: true
      plots.set.flag.tamed-attack: true
      plots.set.flag.tamed-attack.*: true
      plots.set.flag.misc-interact: true
      plots.set.flag.misc-interact.*: true
      plots.set.flag.hanging-place: true
      plots.set.flag.hanging-place.*: true
      plots.set.flag.hanging-break: true
      plots.set.flag.hanging-break.*: true
      plots.set.flag.vehicle-use: true
      plots.set.flag.vehicle-use.*: true
      plots.set.flag.vehicle-place: true
      plots.set.flag.vehicle-place.*: true
      plots.set.flag.vehicle-break: true
      plots.set.flag.vehicle-break.*: true
      plots.set.flag.place: true
      plots.set.flag.place.*: true
      plots.set.flag.break: true
      plots.set.flag.break.*: true
      plots.set.flag.use: true
      plots.set.flag.use.*: true
      plots.set.flag.forcefield: true
      plots.set.flag.forcefield.*: true
      plots.set.flag.price: true
      plots.set.flag.no-worldedit: true
      plots.set.flag.no-worldedit.*: true
  plots.permpack.basicinbox:
    default: false
    children:
      plots.inbox.read.public: true
      plots.inbox.modify.public: true
      plots.inbox.write.public: true
      plots.inbox.read.report: true
      plots.inbox.write.report: true
      plots.inbox.read.owner: true
      plots.inbox.modify.owner: true
      plots.inbox.write.owner: true
      plots.comment: true
      plots.inbox: true
  plots.permpack.wilderness:
    default: false
    children:
      plots.admin.interact.unowned: true
      plots.admin.destroy.unowned: true
      plots.admin.build.unowned: true
      plots.projectile.unowned: true
      plots.admin.vehicle.break.unowned: true
      plots.admin.pve.unowned: true
  plots.permpack.basic:
    default: false
    children:
      plots.use: true
      plots.info: true
      plots.claim: true
      plots.auto: true
      plots.home: true
      plots.clear: true
      plots.delete: true
      plots.music: true
      plots.list: true
      plots.list.mine: true
      plots.list.shared: true
      plots.list.world: true
      plots.list.all: true
      plots.list.forsale: true
      plots.list.unowned: true
      plots.set: true
      plots.visit: true
      plots.visit.owned: true
      plots.visit.shared: true
      plots.set.flag: true
      plots.flag.add: true
      plots.flag.remove: true
      plots.flag.list: true
      plots.flag.info: true
      plots.flag: true
      plots.buy: true
      plots.chat: true
      plots.confirm: true
      plots.toggle: true
      plots.toggle.titles: true
      plots.toggle.chat: true
      plots.toggle.time: true
      plots.set.biome: true
      plots.set.home: true
      plots.alias.set: true
      plots.alias.remove: true
      plots.set.description: true
      plots.description: true
      plots.alias: true
      plots.merge: true
      plots.merge.other: true
      plots.merge.4: true
      plots.unlink: true
      plots.denied: true
      plots.add: true
      plots.trust: true
      plots.deny: true
      plots.remove: true
      plots.untrust: true
      plots.undeny: true
      plots.kick: true
      plots.download: true
      plots.save: true
      plots.done: true
      plots.continue: true
      plots.middle: true
